// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package nassauer

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type nassauerNeighborSolicit struct {
	_         structs.HostLayout
	RouterMac struct {
		_ structs.HostLayout
		A uint8
		B uint8
		C uint8
		D uint8
		E uint8
		F uint8
	}
	RouterAddr struct {
		_      structs.HostLayout
		Octets [16]uint8
	}
	DestAddr struct {
		_      structs.HostLayout
		Octets [16]uint8
	}
	TargetAddr struct {
		_      structs.HostLayout
		Octets [16]uint8
	}
}

// loadNassauer returns the embedded CollectionSpec for nassauer.
func loadNassauer() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_NassauerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load nassauer: %w", err)
	}

	return spec, err
}

// loadNassauerObjects loads nassauer and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*nassauerObjects
//	*nassauerPrograms
//	*nassauerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadNassauerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadNassauer()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// nassauerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type nassauerSpecs struct {
	nassauerProgramSpecs
	nassauerMapSpecs
	nassauerVariableSpecs
}

// nassauerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type nassauerProgramSpecs struct {
	Nassauer *ebpf.ProgramSpec `ebpf:"nassauer"`
}

// nassauerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type nassauerMapSpecs struct {
	AYA_LOGS     *ebpf.MapSpec `ebpf:"AYA_LOGS"`
	IPV6PREFIXES *ebpf.MapSpec `ebpf:"IPV6_PREFIXES"`
	SOLICIT      *ebpf.MapSpec `ebpf:"SOLICIT"`
}

// nassauerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type nassauerVariableSpecs struct {
	AYA_LOG_LEVEL *ebpf.VariableSpec `ebpf:"AYA_LOG_LEVEL"`
	VERSION       *ebpf.VariableSpec `ebpf:"VERSION"`
}

// nassauerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadNassauerObjects or ebpf.CollectionSpec.LoadAndAssign.
type nassauerObjects struct {
	nassauerPrograms
	nassauerMaps
	nassauerVariables
}

func (o *nassauerObjects) Close() error {
	return _NassauerClose(
		&o.nassauerPrograms,
		&o.nassauerMaps,
	)
}

// nassauerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadNassauerObjects or ebpf.CollectionSpec.LoadAndAssign.
type nassauerMaps struct {
	AYA_LOGS     *ebpf.Map `ebpf:"AYA_LOGS"`
	IPV6PREFIXES *ebpf.Map `ebpf:"IPV6_PREFIXES"`
	SOLICIT      *ebpf.Map `ebpf:"SOLICIT"`
}

func (m *nassauerMaps) Close() error {
	return _NassauerClose(
		m.AYA_LOGS,
		m.IPV6PREFIXES,
		m.SOLICIT,
	)
}

// nassauerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadNassauerObjects or ebpf.CollectionSpec.LoadAndAssign.
type nassauerVariables struct {
	AYA_LOG_LEVEL *ebpf.Variable `ebpf:"AYA_LOG_LEVEL"`
	VERSION       *ebpf.Variable `ebpf:"VERSION"`
}

// nassauerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadNassauerObjects or ebpf.CollectionSpec.LoadAndAssign.
type nassauerPrograms struct {
	Nassauer *ebpf.Program `ebpf:"nassauer"`
}

func (p *nassauerPrograms) Close() error {
	return _NassauerClose(
		p.Nassauer,
	)
}

func _NassauerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed nassauer-ebpf
var _NassauerBytes []byte
